assign the top contributor as fallback author/maintainer in case none of the metadata specified anything better

diff --git a/codemeta-harvester b/codemeta-harvester
--- a/codemeta-harvester
+++ b/codemeta-harvester
@@ -348,6 +348,22 @@ harvest() {
             fi
             flushlog
 
+
+            cd "$scandir" || die "Unable to enter $scandir"
+            #Set up a fallback in case no authors or maintainers are specified: simply assigns the top contributor
+            if ! git log --pretty=short | git shortlog -s -e | grep -Fv "@noreply" | grep -v "snyk-bot" | grep -v "dependabot" | grep -v "badger@gitter.im" | grep -v dependabot | sort -rn | cut -f 2 | head -n 1 > "$CACHEDIR/tmp/$ID.TOPCONTRIBUTOR"; then
+                error "git shortlog failed"
+                info "Git top contributor $(cat "$CACHEDIR/tmp/$ID.TOPCONTRIBUTOR") will be assigned as author and maintainer if none are set explicitly in the metadata"
+            fi
+            #shellcheck disable=SC2086 #(allow globbing and splitting for $CODEMETAPY_ARGS)
+            if ! codemetapy $CODEMETAPY_ARGS -O "$CACHEDIR/tmp/90-authors.$ID.codemeta.json" -i authors "$CACHEDIR/tmp/$ID.TOPCONTRIBUTOR" 2> "$TMPLOG" >&2; then
+                error "Parsing top contributor failed for $ID (codemetapy failed)"
+            fi
+            #shellcheck disable=SC2086 #(allow globbing and splitting for $CODEMETAPY_ARGS)
+            if ! codemetapy $CODEMETAPY_ARGS -O "$CACHEDIR/tmp/90-maintainers.$ID.codemeta.json" -i maintainers "$CACHEDIR/tmp/$ID.TOPCONTRIBUTOR" 2> "$TMPLOG" >&2; then
+                error "Parsing top contributor failed for $ID (codemetapy failed)"
+            fi
+
             cd "$scandir" || die "Unable to enter $scandir"
             info "Extracting last and first commit date from git log...."
             #alternative: git shortlog --format=format:%cI | grep -vF '(' | sed 's/[[:space:]]//g' |  awk NF | tail -n 1 OR head -1
