obtain and use latest stable release of the software from git (latest git tag according to semantic versioning, if present), allows distinguishing stable branches from development branches (CLARIAH/clariah-plus#33)

diff --git a/codemeta-harvester b/codemeta-harvester
--- a/codemeta-harvester
+++ b/codemeta-harvester
@@ -80,7 +80,7 @@ harvest() {
         fi
     elif [ -e setup.py ]; then
         info "found python setup for $ID, converting to codemeta"
-        if ! codemetapy --with-entrypoints > "$OUTPUTDIR/$ID.codemeta.json"; then
+        if ! codemetapy --with-entrypoints -o "$OUTPUTDIR/$ID.codemeta.json"; then
             rm "$OUTDIR/$ID.codemeta.json" 2>/dev/null #clean up possible partial output
             error "python setup.py to codemeta conversion failed (codemetapy failed)"
             return 1
@@ -91,18 +91,40 @@ harvest() {
     fi
 }
 
+get_latest_version() {
+    #Finds the latest git tag or falls back to returning the git default branch (usually master or main)
+    #Assumes some kind of semantic versioning (possibly with a v prefix)
+    TAG=$(git tag -l | grep -E "^v?[0-9]+(\.[0-9])*" | sort -t. -k 1.2,1n -k 2,2n -k 3,3n -k 4,4n)
+    if [ -z "$TAG"]; then
+        info "No releases found, falling back to default git branch!"
+        git_default_branch
+    fi
+}
+
+git_default_branch() {
+    #output the git default branch for the repository in the current working dir (usually master or main)
+    git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@'
+}
+
 process() {
     #read a configuration file and harvest the source
     CONFIGFILE="$1"
     ID=$(basename "$CONFIGFILE" | sed -e 's/\.yaml//' -e 's/\.yml//')
     SOURCEREPO=$(dasel -r yaml ".source" < "$CONFIGFILE")
+    #Get the requested ref (branch or tag or commit) from the config (if present, otherwise the latest tag will be extracted automatically)
+    REF=$(dasel -r yaml ".ref" < "$CONFIGFILE")
     if [ -z "$SOURCEREPO" ]; then
         die "invalid configuration: $ID"
     fi
     info "Processing $ID ($SOURCEREPO)"
     if [ -d "$CACHEDIR/$ID" ]; then
         cd "$CACHEDIR/$ID" || die "failed to enter directory $CACHEDIR/$ID"
-        if git pull; then
+        if git pull --tags; then
+            if [ -n "$REF" ]; then
+                REF=$(get_latest_version)
+            fi
+            info "Using $REF"
+            git checkout "$REF" || die "Invalid git ref '$REF' or unclean working dir"
             harvest "$ID"
         else
             error "Failed to git pull $SOURCEREPO"
@@ -112,6 +134,11 @@ process() {
         cd "$CACHEDIR" || die "failed to enter cache directory $CACHEDIR"
         if git clone "$SOURCEREPO" "$CACHEDIR/$ID"; then
             cd "$CACHEDIR/$ID" || die "failed to enter dir $CACHEDIR/$ID"
+            if [ -n "$REF" ]; then
+                REF=$(get_latest_version)
+            fi
+            info "Using $REF"
+            git checkout "$REF" || die "Invalid git ref '$REF' or unclean working dir"
             harvest "$ID"
         else
             error "Failed to git clone $SOURCEREPO"
