implemented --strict mode that aborts a conversion when a main component fails, new default behaviour is to be more permissive and carry on (CLARIAH/clariah-plus#33)

diff --git a/codemeta-harvester b/codemeta-harvester
--- a/codemeta-harvester
+++ b/codemeta-harvester
@@ -40,7 +40,7 @@ flushlog() {
 }
 
 usage() {
-    echo "codemeta-harvester [--debug] [--ignore] [--cachedir path] [--baseuri uri] [--outputdir path] [--opts codemetapy-options] [CONFIG_FILE_OR_DIRECTORY] ...">&2
+    echo "codemeta-harvester [--debug] [--ignore] [--strict] [--cachedir path] [--baseuri uri] [--outputdir path] [--opts codemetapy-options] [CONFIG_FILE_OR_DIRECTORY] ...">&2
     echo "   This tool harvests software metadata from source code repositories and makes it available as codemeta."
     echo "   If not file or directory is specified, the harvester will attempt to extract" >&2
     echo "   software metadata for the project in the current working directory and write a codemeta.json file there." >&2
@@ -53,6 +53,7 @@ usage() {
     echo "  --cachedir [PATH]   Directory to use for caching and storage of temporary files, all git repos will be cloned here">&2
     echo "  --debug             Output all logs"
     echo "  --keep              Keep intermediate output (in cachedir), don't clean up (useful for debugging)"
+    echo "  --strict            Fail a conversion if one of it's main components fails"
     echo "  --stdout            Don't write files but output to stdout"
 }
 
@@ -71,6 +72,7 @@ CACHEDIR="$TMPDIR/codemeta-harvester.cache/"
 KEEPCACHE=0
 IGNORE=0
 CLEAN_README=0
+STRICT=0
 OUTPUTDIR=$(realpath .)
 CODEMETAPY_ARGS=""
 
@@ -104,6 +106,9 @@ while :; do
         --identifier)
             IDENTIFIER="$2"
             shift
+            ;;
+        --strict)
+            STRICT=1
             ;;
         --opts)
             CODEMETAPY_ARGS="$CODEMETAPY_ARGS $2"
@@ -153,7 +158,7 @@ harvest() {
                 #                               ^-- lowest number indicates highest priority
             else
                 error "codemeta.json for $ID is not well-formed"
-                return 1
+                [ $STRICT -eq 1 ] && return 1
             fi
         else
             #No codemeta found, automatically extract from other sources.
@@ -169,7 +174,7 @@ harvest() {
                     #                               ^-- lowest number indicates highest priority
                 else
                     error "codemeta-harvest.json for $ID is not well-formed"
-                    return 1
+                    [ $STRICT -eq 1 ] && return 1
                 fi
             fi
 
@@ -178,7 +183,7 @@ harvest() {
                     info "found CITATION.cff for $ID, converting to codemeta"
                     if ! cffconvert -i "$f" -o "$CACHEDIR/tmp/10-citationcff.$ID.codemeta.json" -f codemeta 2> "$TMPLOG" >&2; then
                         error "CITATION.cff to codemeta conversion for $ID failed"
-                        return 1
+                        [ $STRICT -eq 1 ] && return 1
                     fi
                     flushlog
                     break
@@ -190,7 +195,7 @@ harvest() {
                 #shellcheck disable=SC2086 #(allow globbing and splitting for $CODEMETAPY_ARGS)
                 if ! codemetapy $CODEMETAPY_ARGS -O "$CACHEDIR/tmp/20-python.$ID.codemeta.json" 2> "$TMPLOG" >&2; then
                     error "python setup.py to codemeta conversion failed (codemetapy failed)"
-                    return 1
+                    [ $STRICT -eq 1 ] && return 1
                 fi
                 flushlog
             fi
@@ -200,7 +205,7 @@ harvest() {
                 #shellcheck disable=SC2086 #(allow globbing and splitting for $CODEMETAPY_ARGS)
                 if ! codemetapy $CODEMETAPY_ARGS -O "$CACHEDIR/tmp/21-java.$ID.codemeta.json" pom.xml 2> "$TMPLOG" >&2; then
                     error "pom.xml to codemeta conversion failed (codemetapy failed)"
-                    return 1
+                    [ $STRICT -eq 1 ] && return 1
                 fi
                 flushlog
             fi
@@ -210,7 +215,7 @@ harvest() {
                 #shellcheck disable=SC2086 #(allow globbing and splitting for $CODEMETAPY_ARGS)
                 if ! codemetapy $CODEMETAPY_ARGS -O "$CACHEDIR/tmp/22-npm.$ID.codemeta.json" package.json 2> "$TMPLOG" >&2; then
                     error "package.json to codemeta conversion failed (codemetapy failed)"
-                    return 1
+                    [ $STRICT -eq 1 ] && return 1
                 fi
                 flushlog
             fi
