cleanup after merge, removed "or web scraping" #1

diff --git a/codemeta-harvester b/codemeta-harvester
--- a/codemeta-harvester
+++ b/codemeta-harvester
@@ -286,12 +286,10 @@ harvest() {
             fi
 
             GIT_REMOTE_URL=$(git remote get-url origin | sed 's|git@|https://|' | sed "s|\.git$||")
-            #check=$(echo $GIT_REMOTE_URL | grep "https://github.com/\|https://gitlab.com/")
-            #if  [ -n "$check" ] || [ -n "$GITHUB_TOKEN" ] || [ -n "$GITLAB_TOKEN" ]; then
-            info "Querying Github/GitLab API or WebPage scraping ($GIT_REMOTE_URL)"
+            info "Querying Github/GitLab API ($GIT_REMOTE_URL)"
             #shellcheck disable=SC2086 #(allow globbing and splitting for $CODEMETAPY_ARGS)
-            if ! codemetapy $CODEMETAPY_ARGS -O "$CACHEDIR/tmp/40-gitapi-web.$ID.codemeta.json" "$GIT_REMOTE_URL" 2> "$TMPLOG" >&2; then
-                error "conversion from Github/GitLab API or WebPage scraping query failed for $ID ($GIT_REMOTE_URL) (codemetapy failed)"
+            if ! codemetapy $CODEMETAPY_ARGS -O "$CACHEDIR/tmp/40-gitapi.$ID.codemeta.json" "$GIT_REMOTE_URL" 2> "$TMPLOG" >&2; then
+                error "conversion from Github/GitLab API query failed for $ID ($GIT_REMOTE_URL) (codemetapy failed)"
             fi
             flushlog
 
