First version to execute and parse linguist information

diff --git a/codemeta-harvester b/codemeta-harvester
--- a/codemeta-harvester
+++ b/codemeta-harvester
@@ -73,7 +73,7 @@ usage() {
 }
 
 missing=0
-DEPENDENCIES="git sed python3 dasel codemetapy cffconvert recode awk"
+DEPENDENCIES="git sed python3 dasel codemetapy cffconvert recode awk github-linguist"
 for dependency in $DEPENDENCIES; do
     if ! command -v "$dependency" >/dev/null 2>/dev/null; then
         error "dependency $dependency not found" && missing=1
@@ -231,7 +231,7 @@ harvest() {
             fi
 
             cd "$scandir" || die "Unable to enter $scandir"
-            for f in CITATION.cff CITATION.CFF CITATION; do
+            for f in CITATION.cff CITATION.CFF CITATION citation.cff; do
                 if [ -e "$f" ]; then
                     info "found CITATION.cff for $ID, converting to codemeta"
                     if ! cffconvert -i "$f" -o "$CACHEDIR/tmp/12-citationcff.$ID.codemeta.json" -f codemeta 2> "$TMPLOG" >&2; then
@@ -244,7 +244,7 @@ harvest() {
             done
 
             cd "$scandir" || die "Unable to enter $scandir"
-            if [ -e setup.py ] || [ -e pyproject.toml ]; then
+            if [ -e setup.py ] || [ -e pyproject.toml ]; then #setup.json
                 info "found python setup for $ID, converting to codemeta"
                 #shellcheck disable=SC2086 #(allow globbing and splitting for $CODEMETAPY_ARGS)
                 if ! codemetapy $CODEMETAPY_ARGS -O "$CACHEDIR/tmp/20-python.$ID.codemeta.json" 2> "$TMPLOG" >&2; then
@@ -518,6 +518,9 @@ harvest() {
                 fi
                 flushlog
             fi
+
+
+
         fi
 
         if [ -n "$CURRENT_BRANCH" ]; then
@@ -525,6 +528,12 @@ harvest() {
             cd "$oldcwd" || die "Unable to return to $oldcwd"
         fi
     done
+
+    # run github-linguist
+    cd "$scandir" || die "Unable to enter $scandir"
+    info "Parsing language information from files..."
+    LINGUISTSTATUS=$("$SCRIPTDIR/run-linguist.sh" 2> "$TMPLOG")
+
 
     files=$(ls -r "$CACHEDIR"/tmp/*."$ID".codemeta.json | tr "\n" " ")
 
